# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "9.deployment/model_board")
v <- vetiver_pin_read(b, "depression-southafrica", version = "20260406T190225Z-aa0a9")

#* @plumber
function(pr) {
    pr |> vetiver_api(v)
}
